### ISSUE TITLE
Serialize Uint8Array? 

### ISSUE THREAD

**Issue by FrankC01** [near/borsh-js#14]
noob alert:

I'm trying to serialize a Uint8Array to be sent to Rust WASI expecting a Vec<u8> to de-serialize and am not sure of how to declare the model. What I have is:
 ```
 class AccumulatorSer {
 constructor(value: Uint8Array) 

 { this.accumulator = value; } 

 public accumulator: Uint8Array;
 };

const ACCUMULATOR_SCHEMA = new Map([[AccumulatorSer, 

 { kind: 'struct', fields: [['accumulator', 'Uint8Array']] } 

]]);

// in function
 let in_acc = new AccumulatorSer(Uint8Array.from(tracking_account_state.inputAccumulator.slice(8)));

serialize(ACCUMULATOR_SCHEMA, in_acc);
 ```

I get this error:
 ```
 TypeError: writer<span class="error">[capitalizeFirstLetter(...)]</span> is not a function
 ```

Also, can I avoid having to wrap the Uint8Array in a class to build the schema?

**Comment by jsoneaday** [comment]
I have a similar issue where I'm trying to serialize/deserialize an array of some type. Does anyone know how to do that?

**Comment by igdeman** [comment]
Have similar issue. In my case serialization of Uint8Array works fine but unfortunately deserialization doesn't. I'm sure that buffer i'm pasing for deserialization is filed correctly. 

My model has fields declaration like this:
`
first_name: Uint8Array = new Uint8Array(20);
last_name: Uint8Array = new Uint8Array(20);
username: Uint8Array = new Uint8Array(20);
email: Uint8Array = new Uint8Array(128);
`
Sheme:
`
new Map([
            [UserAccount, { 
                kind: 'struct', 
                fields: [
                    ['first_name', [20]],
                    ['last_name', [20]],
                    ['username', [20]],
                    ['email', [128]],
                ] 
            }],
        ]);
`

**Comment by igdeman** [comment]
> Have similar issue. In my case serialization of Uint8Array works fine but unfortunately deserialization doesn't. I'm sure that buffer i'm pasing for deserialization is filed correctly but result of desserialization is just an empty model.
> 
> My model has fields declaration like this:
> `first_name: Uint8Array = new Uint8Array(20); last_name: Uint8Array = new Uint8Array(20); username: Uint8Array = new Uint8Array(20); email: Uint8Array = new Uint8Array(128);`
> Sheme:
> `new Map([ [UserAccount, { kind: 'struct', fields: [ ['first_name', [20]], ['last_name', [20]], ['username', [20]], ['email', [128]], ] }], ]);`

Actually deserialization also works fine! I have figured out that model class has to have constructor that accepts object with deserialized params.

**Comment by FrankC01** [comment]
@igdeman Can you post a simple working model that succeeds? Thanks...

**Comment by jsoneaday** [comment]
But what if you have an array of UserAccount? How do you handle that?

**Comment by jsoneaday** [comment]
@igdeman I'm not sure what you mean by object with deserialized params. For example here is my own model below. How would I refactor it in order to allow deserialization of an array of this model type?

`class ChatMessage {
  archive_id: string = DUMMY_TX_ID;
  created_on: string = DUMMY_CREATED_ON; // max milliseconds in date
  constructor(
    fields: { archive_id: string; created_on: string } | undefined = undefined
  ) {
    if (fields) {
      this.archive_id = fields.archive_id;
      this.created_on = fields.created_on;
    }
  }
}`

**Comment by igdeman** [comment]
Hi guys, sorry on delay, a bit busy this days :(
Here is working example using TypeScript:
`class Assignable
{
    [index:string]:any;
    constructor(properties:{[index:string]:any}) 
    {
        Object.keys(properties).map((key:string) => {
            this[key] = properties[key];
        });
    }
}
class ModelExample extends Assignable
{
    byteArray?:Uint8Array;
    constructor(properties:{[index:string]:any})
    {
        super(properties);
    }
}
const scheme = new Map([
    [ModelExample, { 
        kind: 'struct', 
        fields: [
            ['byteArray', [10]],
        ] 
    }],
]);

let byteArray = new Uint8Array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
let exampleTest:ModelExample = new ModelExample({byteArray})

let exampleSerialized = borsh.serialize(scheme, exampleTest);
let exampleDeserialized = borsh.deserialize(scheme, ModelExample, Buffer.from(exampleSerialized));

console.log(exampleDeserialized);`

I hope this helps...

**Comment by max-block** [comment]
I still have the error `TypeError: writer[capitalizeFirstLetter(...)] is not a function`

The last example doesn't work for me. It fails with the error.

**Comment by AuroraLantean** [comment]
igdeman thank you so much. Now I can convert bignumber array into string array, then use str.charCodeAt(string_index) to convert each string char into UTF-16 code, which is between 0 and 255.
Also I use convert boolean array into number array, then don't need further conversion.

```
const scheme = new Map([
  [Struct1, { 
      kind: 'struct', 
      fields: [
          ['byteArray1', [dataLength1]],
          ['byteArray2', [dataLength2]],
          ['byteArray3', [dataLength3]],
      ] 
  }],
]);
const byteArray1 = new Uint8Array(utf16Array1);
const byteArray2 = new Uint8Array(utf16Array2);
const byteArray3 = new Uint8Array(utf16Array3);

let obj_input:Struct1 = new Struct1({
  byteArray1: byteArray1,
  byteArray2: byteArray2,
  byteArray3: byteArray3,
});
let serialized = borsh.serialize(scheme, obj_input);
```

**Comment by marcus-pousette** [comment]
I see you found a solution to this, but I want to present a solution of my own, that perhaps makes the code a bit cleaner. 

I am [maintaining a fork](https://github.com/dao-xyz/borsh-ts) of this library that lets you do this

```typescript
class SomeClass {
  @field({ type: fixedArray('u8', 3) }) // Fixed array of length 3
  public fixedLengthArray: number[];
}

... 

let ser = serialize(new SomeClass(...))
let der = deserialize(Buffer.from(ser), SomeClass)
```

You can replace the type "number[]" with UInt8Array and it would also work for serialization but would deserialize into "number[]" natively.

**Comment by gagdiez** [comment]
should be fixed now, please open again if not
