### ISSUE TITLE
How to serialize deserialize an array of some type

### ISSUE THREAD

**Issue by jsoneaday** [near/borsh-js#22]
I am using borsh-js and getting the error Error: Class Array is missing in schema. I would like to deserialize an array of ChatMessage that comes into my js client code as Buffer of u8 array. Note when I deserialize just one class instance it works.

`
 class ChatMessage {
 archive_id: string = DUMMY_TX_ID;
 created_on: string = DUMMY_CREATED_ON; // max milliseconds in date
 constructor(
 fields: 

 { archive_id: string; created_on: string } 

 | undefined = undefined
 ) {
 if (fields) 

 { this.archive_id = fields.archive_id; this.created_on = fields.created_on; } 

 }
 }
 const ChatMessageSchema = new Map([
 [
 ChatMessage,

 { kind: "struct", fields: [ ["archive_id", "String"], ["created_on", "String"], ], } 

,
 ],
 ]);
 const result = serialize(
 ChatMessageSchema,
 sampleChatMessages
 );
 `

**Comment by unordered-set** [comment]
According to my findings, JS bindings does not have this feature at the moment, so I ended up with the following solution:

```
class ChatMessages {
    // borsh does not support list of structs.
    names: string[] = [];
    messages: string[] = [];
}

const ChatMessagesSchema = new Map([
    [ChatMessages, {
        kind: 'struct', fields: [
            ['names', ['string']],
            ['messages', ['string']],
        ]
    }]
]);
```

**Comment by gagdiez** [comment]
should be fixed now, please open again if not
