### ISSUE TITLE
How to serialize a floating point number

### ISSUE THREAD

**Issue by rdelao** [near/borsh-js#25]
I see there is no supported 'f32' or 'f64' types. I am new to typescript so maybe I'm missing something here, but is there a work-around to serialize a `number` type that has a floating point value? Maybe send as a byte array of u8 that reflects IEEE standard?

e.g. 0.0001

**Comment by rdelao** [comment]
For anyone reading, my workaround:

```
// Converts number into a 64-bit binary using its IEEE764 Representation, little endian
function convertNumberToBinary(num: number): Uint8Array {
  let str = "";
  const c = new Uint8Array(new Float64Array([num]).buffer, 0, 8);
  return c;
}


class MySerializedClass {
  my_field = Uint8Array.from([0,0,0,0,0,0,0,0]);
  constructor(fields: { my_field: number } | undefined = undefined) {
    if (fields) {
      this.my_field = convertNumberToBinary(fields.my_field);
    }
  }
}

const MySerializedClassSchema = new Map([
  [MySerializedClass, {kind: 'struct', fields: [['my_field', [8]]]}],
]);

let requestBody = borsh.serialize(
  MySerializedClassSchema,
  new MySerializedClass(
    { my_field: 0.0000001 }
  )
)
```

**Comment by daoplays** [comment]
Can this be generalised if i have an array of f64's in a program data account and i want to deserialise them?

**Comment by marcus-pousette** [comment]
You can use @protobufjs/float package to get reader and writer methods that allows you to modify the buffer in the correct way. Remember that NaN should not be serialized or deserialzed with the Borsh spec but to throw error. 
```typescript 
import { readFloatLE, writeFloatLE, readDoubleLE, writeDoubleLE } from '@protobufjs/float'
```


 or use [@dao-xyz/borsh](https://github.com/dao-xyz/borsh-ts)  where you can do this
 ```typescript
 class MyStruct
 {
     @field({type: 'f32'})
     f32: number 
     
      @field({type: 'f64'})
      f64: number 
 }

 ```

**Comment by ailisp** [comment]
It's now supported in 1.0: https://github.com/near/borsh-js/blob/93a633dfa76d8577b3cb6f5c1a906dfa3b9b63a2/borsh-ts/test/(de)serialize.test.js#L49
