### ISSUE TITLE
`global` is not defined in the browser

### ISSUE THREAD

**Issue by dimfeld** [near/borsh-js#38]
The check for if the `TextDecoder` polyfill is required currently references `global`, which only exists on Node.js and not in the browser.

https://github.com/near/borsh-js/blob/261d9cde21665de5a9e2c75ec2509c0bfb7030bf/borsh-ts/index.ts#L6-L9

With bundlers that don't automatically polyfill `global` this causes problems and requires hacks to make it work. What you would think of one of the following solutions?

- `typeof TextDecoder !== "function" ? encoding.TextDecoder : TextDecoder`
- `typeof globalThis.TextDecoder !== "function" ? encoding.TextDecoder : globalThis.TextDecoder`

`globalThis` has been available for a while now, but I think the first one is best since it doesn't make any assumptions about the name of the global variable. Any thoughts? I'm happy to submit a PR for this.

**Comment by ilyazub** [comment]
Shouldn't the TypeScript compiler check the availability of the `globalThis` variable?

```ts
// cat index.ts 
console.log(global, globalThis, global == globalThis);
```

```bash
$ yarn run tsc index.ts
index.ts:1:13 - error TS2304: Cannot find name 'global'.

1 console.log(global, globalThis, global == globalThis);
              ~~~~~~

index.ts:1:33 - error TS2304: Cannot find name 'global'.

1 console.log(global, globalThis, global == globalThis);
                                  ~~~~~~


Found 2 errors.
```

**Comment by dimfeld** [comment]
This package depends on `@types/node`, which provides the definition of `global` to Typescript. `globalThis` is part of Typescript's built-in type library.

**Comment by glennmichael123** [comment]
@dimfeld any luck on this issue so far? I'm trying to use the solana web3.js library for my Vue.js project but I can't proceed cause of this. it's kinda sad the maintainers aren't fixing this issue.

**Comment by dimfeld** [comment]
I submitted #40 to fix it. No response yet.

**Comment by glennmichael123** [comment]
@dimfeld too bad, in the meantime do you have any idea or any "hacky" tricks to circumvent this?

**Comment by dimfeld** [comment]
Seems like the best solution for now is to add something like this to the top of your app's root HTML file:

```
<script>
    window.global = window;
 </script>
```

Depending on your bundler, you could also use some sort of replacement plugin to change `global.TextDecoder` to just `TextDecoder` or `globalThis.TextDecoder`.

**Comment by volovyk-s** [comment]
Thanks for the fix guys!

**Comment by volovyk-s** [comment]
@dimfeld @glennmichael123 @ilyazub v0.7.0 released!

**Comment by glennmichael123** [comment]
@volovyk-s thank you so much!!
