### ISSUE TITLE
Documentation says nothing about Test object and where it came from.

### ISSUE THREAD

**Issue by dmitryr117** [near/borsh-js#42]
Need more documentation for Test object. Otherwise unclear what it is and how it should be defined.
 ```
 const value = new Test(

 { x: 255, y: 20, z: '123', q: [1, 2, 3] } 

);
 ```
 What is Test? What is its definition?

**Comment by marcus-pousette** [comment]
Read the top of this test file https://github.com/near/borsh-js/blob/master/borsh-ts/test/serialize.test.js

**Comment by samlaf** [comment]
I agree that the Test object should be defined in the docs... or at least that `serialize.test.js` should be linked.

**Comment by gagdiez** [comment]
should be fixed now, please open again if not
