### ISSUE TITLE
Remove dependency on text-encoding-utf-8

### ISSUE THREAD

**Issue by cristobal** [near/borsh-js#47]
1.  1.  Bakground

Should it rather not be up to the user to actually polyfill this dependency when needed?

I tried to setup `near-api-js` with <span class="error">[snowpack]</span>([https://www.snowpack.dev/](https://www.snowpack.dev/)) , and it fails since the `text-encoding-utf-8` library does not use `default export` for the mjs build but rather a normal <span class="error">[`export`]</span>([https://github.com/arv/text-encoding-utf-8/blob/17484662e1e6881accbd69d5e51f3587c901311e/lib/encoding.lib.mjs#L665](https://github.com/arv/text-encoding-utf-8/blob/17484662e1e6881accbd69d5e51f3587c901311e/lib/encoding.lib.mjs#L665)), which gives errors like these:

!<span class="error">[Screenshot 2021-12-02 at 23 08 19]</span>([https://user-images.githubusercontent.com/155505/144511056-97c3567a-423b-4a56-9ddd-683b669c4918.png](https://user-images.githubusercontent.com/155505/144511056-97c3567a-423b-4a56-9ddd-683b669c4918.png))

I hijacked the borsh module and removed the imports on `text-encoding-utf-8`, and stuff still works 👌🏽 

1.  1.  TextEncoder and TextDecoder Support

The `text-encoding-utf-8` library has not been updated in four years (not that it is a bad sign), but the TextEncoder and TextDecoder are largely supported by most browsers now, mostly old Internet Explorer which does not support this and which has now been deprecated and no longer supported.

*   [https://caniuse.com/?search=textencoder](https://caniuse.com/?search=textencoder)
*   [https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder)
*   [https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder)

!<span class="error">[Screenshot 2021-12-02 at 23 01 23]</span>([https://user-images.githubusercontent.com/155505/144510188-b737ffef-ceb7-4e84-a06e-604c07a0f668.png](https://user-images.githubusercontent.com/155505/144510188-b737ffef-ceb7-4e84-a06e-604c07a0f668.png))

1.  1.  Proposal
         Remove the import and dependency on `text-encoding-utf-8` and rather specify in the README that if one needs support for this one should rather polyfill this manually instead.

**Comment by gagdiez** [comment]
should be fixed now, please open again if not
