### ISSUE TITLE
 Buffer is not defined

### ISSUE THREAD

**Issue by ghost** [near/borsh-js#48]
<pre>import 

 {Buffer} 

 from "buffer";
 import 

 {deserialize, serialize} 

 from "borsh";

class Test {
 constructor(data) 

 { Object.assign(this, data); } 

}

const value = new Test(

 { x: 255, y: 20, z: '123', q: [1, 2, 3] } 

);
 const schema = new Map([[Test, 

 { kind: 'struct', fields: [['x', 'u8'], ['y', 'u64'], ['z', 'string'], ['q', [3]]] } 

]]);
 const buffer = serialize(schema, value);</pre>

Does not work

**Comment by steveluscher** [comment]
Fixed by #50.

**Comment by steveluscher** [comment]
`Buffer` still needs to be imported where it’s used. Is that snippet above of code that you own? Try importing `’buffer’` at the top of that file.

**Comment by onuruci** [comment]
`global.Buffer = global.Buffer || require("buffer").Buffer;`

importing globally saved my issue

**Comment by gagdiez** [comment]
we do not use buffer anymore, this is fixed
