### ISSUE TITLE
Support the `bool` type

### ISSUE THREAD

**Issue by defactojob** [near/borsh-js#5]
While the Borsh spec doesn't officially support `bool`, the Rust implementation does map bool to u8 as 1/0.

Can we add `bool` and/or `boolean` to the JS implementation for convenience?

**Comment by defactojob** [comment]
Instead of hardwiring the bool support, we can create a mapper that maps from a borsh fundamental type to a user specified type.

Here is an example of mapping `u8` to `bool`:

```js
function intToBool(i: number) {
  if (i == 0) {
    return false
  } else {
    return true
  }
}

function boolToInt(t: boolean) {
  if (t) {
    return 1
  } else {
    return 0
  }
}

const boolMapper = {
  encode: boolToInt,
  decode: intToBool
}
```

And in the schema specify the field mapper after the type:

```
{
      kind: "struct",
      fields: [
        ["isInitialized", "u8", boolMapper],
      ],
    }
```

**Comment by beautyfree** [comment]
+1

**Comment by ailisp** [comment]
It's supported in 1.0!
