### ISSUE TITLE
Can I use borsh-js directly from HTML script tag instead of node?

### ISSUE THREAD

**Issue by digitalnetbizz** [near/borsh-js#51]
I would like some sort of confirmation that borsh-js ([https://github.com/near/borsh-js](https://github.com/near/borsh-js)) can only be used in node? I would like to use it directly in HTML Javascript using script tag. So far, I've not seen anyone using it that way. I tried to make a copy of the index.js (within the git above) and reference directly from script within my HTML. It throws error.

**Comment by gagdiez** [comment]
the new version should work perfectly in a web
