### ISSUE TITLE
deserialize method not mapping properties properly

### ISSUE THREAD

**Issue by Pr4v33n23** [near/borsh-js#54]
Hi I have a class type defined with schema mentioned below 

`class CampaignDetails {
 name: string
 description: string
 image_link: string
 admin: Buffer
 amount_donated: number

 constructor()
 constructor(
 name?: string,
 description?: string,
 image_link?: string,
 admin?: Buffer,
 amount_donated?: number
 ) 

 { ;(this.name = name!), (this.description = description!), (this.image_link = image_link!), (this.admin = admin!), (this.amount_donated = amount_donated!) } 

 static schema: any = new Map([
 [
 CampaignDetails,

 { kind: 'struct', fields: [ ['admin', [32]], ['name', 'string'], ['description', 'string'], ['image_link', 'string'], ['amount_donated', 'u64'], ], } 

,
 ],
 ])
 }`

but when it deserialize the data the structure of it is changing, 

`CampaignDetails
 admin: undefined
 amount_donated: undefined
 description: undefined
 image_link: undefined
 name:
 admin: Uint8Array(32) <span class="error">[245, 127, 181, 215, 162, 110, 87, 142, 194, 140, 167, 145, 235, 30, 49, 124, 184, 88, 251, 208, 221, 249, 65, 163, 2, 122, 182, 245, 58, 188, 96, 142, buffer: ArrayBuffer(32), byteLength: 32, byteOffset: 0, length: 32, Symbol(Symbol.toStringTag): 'Uint8Array']</span>
 amount_donated: BN 

 {negative: 0, words: Array(3), length: 1, red: null} 

description: "dogs are the best"
 image_link: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg?crop=0.752xw:1.00xh;0.175xw,0&resize=640:*"
 name: "Save dogs"
 [<span class="error">[Prototype]</span>]: Object
 [<span class="error">[Prototype]</span>]: Object`

below is the code for deserializing

` const getAllCampaigns = async () => {
 let accounts = await connection.getProgramAccounts(programId)

 accounts.forEach(![](/images/icons/emoticons/error.png) => 

 { let campaignData = deserialize( CampaignDetails.schema, //@ts-ignore CampaignDetails, x.account.data ) console.log(campaignData) } 

)
 }`

**Comment by marcus-pousette** [comment]
Some of the fields in you class seems to be optional, but the Schema you have created makes all fields required. When you have optional types there will be a byte 0 or 1 indicating if the option is null or not. I think you need to add this to the schema. 

If you find it complicated I would recommend you to use a Typescript implementation of borsh I have created [@dao-xyz/borsh](https://github.com/dao-xyz/borsh-ts). It makes these kind of work a lot easier
