### ISSUE TITLE
TypeError: reader[capitalizeFirstLetter(...)] is not a function

### ISSUE THREAD

**Issue by smacrineanu** [near/borsh-js#61]
I am getting this error in an Angular14 project while trying to deserialize/decode a Uint8Array array.

```
ERROR Error: Uncaught (in promise): TypeError: reader[capitalizeFirstLetter(...)] is not a function
TypeError: reader[capitalizeFirstLetter(...)] is not a function
    at deserializeField (index.js:356:20)
    at deserializeStruct (index.js:410:33)
    at deserializeUnchecked (index.js:438:12)
```

**Comment by marcus-pousette** [comment]
Sounds like ```capitalizeFirstLetter(...)]``` resolves something that reader does not have a property for. 

Can you log ```capitalizeFirstLetter(...)]``` ? Check if you schema does not use any types that are not supported

**Comment by haris-aqeel** [comment]
I am facing the exact same issue in my node-js application. Same piece of code, when used on frontend with Nextjs works perfectly. Please resolve this issue
