### ISSUE TITLE
Serialize primitives (not structs)?

### ISSUE THREAD

**Issue by taoeffect** [near/borsh-js#67]
Is there a way to serialize a primitive without wrapping it in a struct? Does Borsh support that?

**Comment by cy6581** [comment]
Unfortunately in the current version 0.7.x, seems like there's no way than using a wrapper class, even though the wrapper technically adds nothing to the serialized output. The wrapper [class must either declare a Struct or Enum](https://github.com/near/borsh-js/blob/6db74764cedb88097bd6d5636407f0b3481fba4c/borsh-ts/index.ts#L348).

**Comment by ailisp** [comment]
It's now supported in 1.0! See readme.md
