### ISSUE TITLE
How to deserialize enum?

### ISSUE THREAD

**Issue by kayac-chang** [near/borsh-js#73]
In the readme, the documentation mentions about enum.
```
{ enum: [{ className1: { struct: {...} } }, { className2: { struct: {...} } }, ... ] } - an enum. The variants of the enum are described by the className1, className2, etc. fields. The variants are structs.
```

But the current implementation seems not correct.
 https://github.com/near/borsh-js/blob/93a633dfa76d8577b3cb6f5c1a906dfa3b9b63a2/borsh-ts/deserialize.ts#L82

**Comment by ailisp** [comment]
Hi @kayac-chang ! Thanks for reporting, the readme is outdated, we've just updated readme.
