### ISSUE TITLE
How to (de)serialize unnamed fields

### ISSUE THREAD

**Issue by kayac-chang** [near/borsh-js#80]
In https://borsh.io/, the specification mentions there are unnamed fields, 
but don't mention it in the documentation.

Suppose we have type `(u64, u64, u64, u8, Option<u8>, u64)`,
how did we (de)serialize with this type?

**Comment by hanakannzashi** [comment]
I also want to know if tuple is supported

**Comment by gagdiez** [comment]
@kayac-chang indeed, not every `Rust` has a 1:1 mapping with `Javascript` types.

`unnamed fields` will be serialized in memory as: [u64, u64, u64, u8, option-bit, u8, u64], so a `Class/Interface` that follows that pattern will be able to deserialize it. The solution proposed by @hanakannzashi is a valid one.

Note: The names in the fields only help to know where to put the deserialised value in the object being created.
